FROM centos:7
MAINTAINER Chester4096 <chester4096@bonio.com.tw>
RUN yum update -y && yum install which gem -y
RUN gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
RUN  \curl -sSL https://get.rvm.io | bash -s stable
RUN source /etc/profile.d/rvm.sh
RUN /usr/local/rvm/bin/rvm install 2.1.7
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
RUN nvm install v6.2.0
RUN yum install -y ImageMagick
